---
apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: dov-deploy 
  namespace: myns 
  labels:
    app: dov
    name: dov-deploy 
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: myapp 
      dept: eng
      commit: abc123
  template: 
    metadata:
      name: mypod
      namespace: myns
      labels:
        app: myapp 
        dept: eng
        commit: abc123
    spec:
      containers:
      - name: mypod-container
        image: chukmunnlee/dov-bear@sha256:483038792aba29562a4d2044e790d7d3e7e6e6f684ce1fcafc3864949c000224
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: INSTANCE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: INSTANCE_HASH
          valueFrom: 
            fieldRef:
              fieldPath: metadata.labels['pod-template-hash']
    