---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: bgg-gw
  namespace: bggns
  labels:
    app: bgg
    name: bgg-gw
spec:
  gatewayClassName: nginx
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    hostname: "*.146.190.195.211.nip.io"

---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: bgg-httproute
  namespace: bggns
  labels:
    app: bgg
    name: bgg-httproute
spec:
  parentRefs:
  - name: bgg-gw
    sectionName: http
  hostnames:
  - bgg.146.190.195.211.nip.io
  rules:
  - matches:
    - path: 
        type: PathPrefix
        value: /
    backendRefs:
    - name: bggapp-svc
      port: 80
